spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
server:
  port: 8002

#  mybatis的配置
mybatis:
  type-aliases-package: com.wonand.pojo
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#    spring的配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8
    username: root
    password: wad123456

# eureka的配置,服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/,http://eureka6003.com:6003/eureka/  #巨坑巨坑巨坑！！！：后面一定要加eureka
  instance:
    instance-id: springcloud-provider-dept8002


#info配置
info:
  app.name: 王安东-springcloud
  company.name: 南十大


