---
server:
  port: 6001

spring:
  profiles: dev
  application:
    name: springcloud-config-eureka

eureka:
  instance:
    hostname: eureka6001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #单机：defaultZone: http://${eureka.instance.hostname}:${server.port}/
      #集群(关联)：
      defaultZone: http://eureka6002.com:6002/eureka/,http://eureka6003.com:6003/eureka/


---
server:
  port: 6001

spring:
  profiles: test
  application:
    name: springcloud-config-eureka

eureka:
  instance:
    hostname: eureka6001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #单机：defaultZone: http://${eureka.instance.hostname}:${server.port}/
      #集群(关联)：
      defaultZone: http://eureka6002.com:6002/eureka/,http://eureka6003.com:6003/eureka/


